In [46]:
import praw
import pandas as pd
import datetime as dt
import logging
import numpy as np
from numpy import random
import nltk
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.metrics import accuracy_score, confusion_matrix
import matplotlib.pyplot as plt
from nltk.corpus import stopwords
import re
from bs4 import BeautifulSoup
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.metrics import classification_report

In [71]:
def logisticreg(X_train, X_test, y_train, y_test):
    from sklearn.linear_model import LogisticRegression
    logmodel = LogisticRegression(C=1e3)
    logmodel.fit(X_train,y_train)
    predictions = logmodel.predict(X_test)
    from sklearn.metrics import classification_report
    print(classification_report(y_test,predictions))
    from sklearn.metrics import confusion_matrix
    print(confusion_matrix(y_test,predictions))
    score = logmodel.score(X_test, y_test)
    print(score)

In [78]:
def train_test(X,y):
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state = 42)

#     print("Results of Logistic Regression")
#     logisticreg(X_train, X_test, y_train, y_test)
    
#     print("svm")
#     svm(X_train, X_test, y_train, y_test)
    print('random forest')
    rand(X_train, X_test, y_train, y_test)

In [79]:

df =pd.read_csv('../Datasets/ML_vars/0001.csv')
for i in range(1,18):
    stri=''
    if i<=8:
        stri+='0'+str(i)+'0'+str(i+1)
    elif i==9:
        stri+='0'+str(i)+str(i+1)
    else:
        stri+=str(i)+str(i+1)    
    temp_df=pd.read_csv('../Datasets/ML_vars/{}.csv'.format(stri))
    df=pd.concat([df,temp_df],sort =False)

In [80]:
df

Unnamed: 0      Date        HomeTeam        AwayTeam  FTHG  FTAG  \
0             0  19/08/00        Charlton        Man City     4     0   
1             1  19/08/00         Chelsea        West Ham     4     2   
2             2  19/08/00        Coventry   Middlesbrough     1     3   
3             3  19/08/00           Derby     Southampton     2     2   
4             4  19/08/00           Leeds         Everton     2     0   
5             5  19/08/00       Leicester     Aston Villa     0     0   
6             6  19/08/00       Liverpool        Bradford     1     0   
7             7  19/08/00      Sunderland         Arsenal     1     0   
8             8  19/08/00       Tottenham         Ipswich     3     1   
9             9  20/08/00      Man United       Newcastle     2     0   
10           10  21/08/00         Arsenal       Liverpool     2     0   
11           11  22/08/00        Bradford         Chelsea     2     0   
12           12  22/08/00         Ipswich      Man United     1     1   
13           13  22/08/00   Middlesbrough       Tottenham     1     1   
14           14  23/08/00         Everton        Charlton     3     0   
15           15  23/08/00        Man City      Sunderland     4     2   
16           16  23/08/00       Newcastle           Derby     3     2   
17           17  23/08/00     Southampton        Coventry     1     2   
18           18  23/08/00        West Ham       Leicester     0     1   
19           19  26/08/00         Arsenal        Charlton     5     3   
20           20  26/08/00        Bradford       Leicester     0     0   
21           21  26/08/00         Everton           Derby     2     2   
22           22  26/08/00         Ipswich      Sunderland     1     0   
23           23  26/08/00        Man City        Coventry     1     2   
24           24  26/08/00   Middlesbrough           Leeds     1     2   
25           25  26/08/00       Newcastle       Tottenham     2     0   
26           26  26/08/00     Southampton       Liverpool     3     3   
27           27  26/08/00        West Ham      Man United     2     2   
28           28  27/08/00     Aston Villa         Chelsea     1     1   
29           29  05/09/00           Leeds        Man City     1     2   
..          ...       ...             ...             ...   ...   ...   
350         350  28/04/18         Swansea         Chelsea     0     1   
351         351  29/04/18      Man United         Arsenal     2     1   
352         352  29/04/18        West Ham        Man City     1     4   
353         353  30/04/18       Tottenham         Watford     2     0   
354         354  04/05/18        Brighton      Man United     1     0   
355         355  05/05/18     Bournemouth         Swansea     1     0   
356         356  05/05/18         Everton     Southampton     1     1   
357         357  05/05/18       Leicester        West Ham     0     2   
358         358  05/05/18           Stoke  Crystal Palace     1     2   
359         359  05/05/18         Watford       Newcastle     2     1   
360         360  05/05/18       West Brom       Tottenham     1     0   
361         361  06/05/18         Arsenal         Burnley     5     0   
362         362  06/05/18         Chelsea       Liverpool     1     0   
363         363  06/05/18        Man City    Huddersfield     0     0   
364         364  08/05/18         Swansea     Southampton     0     1   
365         365  09/05/18         Chelsea    Huddersfield     1     1   
366         366  09/05/18       Leicester         Arsenal     3     1   
367         367  09/05/18        Man City        Brighton     3     1   
368         368  09/05/18       Tottenham       Newcastle     1     0   
369         369  10/05/18        West Ham      Man United     0     0   
370         370  13/05/18         Burnley     Bournemouth     1     2   
371         371  13/05/18  Crystal Palace       West Brom     2     0   
372         372  13/05/18    Huddersfield         Arsenal     0

In [81]:
Home = pd.get_dummies(df['HomeTeam'],drop_first=True)
Away = pd.get_dummies(df['AwayTeam'],drop_first=True)
df.drop(['HomeTeam','AwayTeam'],axis=1,inplace=True)
df = pd.concat([df,Home,Away],axis=1)

In [82]:
df.columns

Index(['Unnamed: 0', 'Date', 'FTHG', 'FTAG', 'HomeResult', 'AwayResult',
       'scoredhome', 'scoredaway', 'concededhome', 'concededaway', 'winshome',
       'winsaway', 'Aston Villa', 'Birmingham', 'Blackburn', 'Blackpool',
       'Bolton', 'Bournemouth', 'Bradford', 'Brighton', 'Burnley', 'Cardiff',
       'Charlton', 'Chelsea', 'Coventry', 'Crystal Palace', 'Derby', 'Everton',
       'Fulham', 'Huddersfield', 'Hull', 'Ipswich', 'Leeds', 'Leicester',
       'Liverpool', 'Man City', 'Man United', 'Middlesboro', 'Middlesbrough',
       'Newcastle', 'Norwich', 'Portsmouth', 'QPR', 'Reading',
       'Sheffield United', 'Southampton', 'Stoke', 'Sunderland', 'Swansea',
       'Tottenham', 'Watford', 'West Brom', 'West Ham', 'Wigan', 'Wolves',
       'Aston Villa', 'Birmingham', 'Blackburn', 'Blackpool', 'Bolton',
       'Bournemouth', 'Bradford', 'Brighton', 'Burnley', 'Cardiff', 'Charlton',
       'Chelsea', 'Coventry', 'Crystal Palace', 'Derby', 'Everton', 'Fulham',
       'Huddersfield

In [83]:
# X=df[['FTHG', 'FTAG', 'scoredhome', 'scoredaway', 'concededhome', 'concededaway',
#        'winshome', 'winsaway', 'Bournemouth', 'Brighton', 'Burnley', 'Cardiff',
#        'Chelsea', 'Crystal Palace', 'Everton', 'Fulham', 'Huddersfield',
#        'Leicester', 'Liverpool', 'Man City', 'Man United', 'Newcastle',
#        'Southampton', 'Tottenham', 'Watford', 'West Ham', 'Wolves',
#        'Bournemouth', 'Brighton', 'Burnley', 'Cardiff', 'Chelsea',
#        'Crystal Palace', 'Everton', 'Fulham', 'Huddersfield', 'Leicester',
#        'Liverpool', 'Man City', 'Man United', 'Newcastle', 'Southampton',
#        'Tottenham', 'Watford', 'West Ham', 'Wolves']]
X=df.drop(['Unnamed: 0', 'Date', 'HomeResult', 'AwayResult','FTHG','FTAG'],axis =1)

In [84]:
X.columns

Index(['scoredhome', 'scoredaway', 'concededhome', 'concededaway', 'winshome',
       'winsaway', 'Aston Villa', 'Birmingham', 'Blackburn', 'Blackpool',
       'Bolton', 'Bournemouth', 'Bradford', 'Brighton', 'Burnley', 'Cardiff',
       'Charlton', 'Chelsea', 'Coventry', 'Crystal Palace', 'Derby', 'Everton',
       'Fulham', 'Huddersfield', 'Hull', 'Ipswich', 'Leeds', 'Leicester',
       'Liverpool', 'Man City', 'Man United', 'Middlesboro', 'Middlesbrough',
       'Newcastle', 'Norwich', 'Portsmouth', 'QPR', 'Reading',
       'Sheffield United', 'Southampton', 'Stoke', 'Sunderland', 'Swansea',
       'Tottenham', 'Watford', 'West Brom', 'West Ham', 'Wigan', 'Wolves',
       'Aston Villa', 'Birmingham', 'Blackburn', 'Blackpool', 'Bolton',
       'Bournemouth', 'Bradford', 'Brighton', 'Burnley', 'Cardiff', 'Charlton',
       'Chelsea', 'Coventry', 'Crystal Palace', 'Derby', 'Everton', 'Fulham',
       'Huddersfield', 'Hull', 'Ipswich', 'Leeds', 'Leicester', 'Liverpool',
       'Man City

In [85]:
y=df[['HomeResult']]*10

In [86]:
y=y.astype(int)

In [87]:
def svm(X_train, X_test, y_train, y_test):
    from sklearn.svm import SVC
    from sklearn.metrics import accuracy_score

    clf = SVC(kernel='linear')
    clf.fit(X_train,y_train)
    y_pred = clf.predict(X_test)
    print(accuracy_score(y_test,y_pred))
    from sklearn.metrics import classification_report
    print(classification_report(y_test,y_pred))
    from sklearn.metrics import confusion_matrix
    print(confusion_matrix(y_test,y_pred))
    score = logmodel.score(X_test, y_test)
    print(score)

In [98]:
def rand(X_train, X_test, y_train, y_test):
    from sklearn.ensemble import RandomForestClassifier

    #Create a Gaussian Classifier
    clf=RandomForestClassifier(n_estimators=100)
    #Train the model using the training sets y_pred=clf.predict(X_test)
    clf.fit(X_train,y_train)
    y_pred=clf.predict(X_test)
    print(accuracy_score(y_test,y_pred))
    from sklearn.metrics import classification_report
    print(classification_report(y_test,y_pred))
    from sklearn.metrics import confusion_matrix
    print(confusion_matrix(y_test,y_pred))
    score = clf.score(X_test, y_test)
    print(score)

In [99]:
train_test(X,y)

random forest


/home/jushaan/Downloads/yes/lib/python3.7/site-packages/ipykernel_launcher.py:7: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  import sys


0.628167641325536
              precision    recall  f1-score   support

           0       0.62      0.64      0.63       589
           5       0.47      0.26      0.34       504
          10       0.67      0.81      0.73       959

    accuracy                           0.63      2052
   macro avg       0.59      0.57      0.57      2052
weighted avg       0.61      0.63      0.61      2052

[[378  67 144]
 [132 132 240]
 [ 96  84 779]]
0.628167641325536
